#!/bin/sh
set -e
export CPPFLAGS="-DNDEBUG"
export CFLAGS="-O2"
export CXXFLAGS="-O2"
export PKG_OS="mingw"
export PKG_ARCH="x86_64"
while [ $# -gt 0 ]; do
  PKG_SCRIPTNAME=$1
  shift
  ./$PKG_SCRIPTNAME
done
