#!/bin/sh
set -e
while [ $# -gt 0 ]; do
  PKG_SCRIPTNAME=$1
  shift

  PKG_ARCH=x86_64
  export CPP="clang -E"
  export AR=ar
  export AS=as
  export NM=nm
  export CC=clang
  export CXX=clang++
  export LD=ld
  export RANLIB=ranlib
  export STRIP=strip
  export CFLAGS="-O2 ${CFLAGS}"
  export CXXFLAGS="-O2 ${CXXFLAGS}"
  export PKG_OS=macos
  export PKG_ARCH

  ./$PKG_SCRIPTNAME
done
