#!/bin/sh
set -e
export CPPFLAGS="-DNDEBUG ${CPPFLAGS}"
export CFLAGS="-O2 ${CFLAGS}"
export CXXFLAGS="-O2 ${CXXFLAGS}"
export PKG_OS="mingw"
export PKG_ARCH="x86_64"
while [ $# -gt 0 ]; do
  PKG_SCRIPTNAME=$1
  shift
  ./$PKG_SCRIPTNAME
done
