#!/bin/sh
set -e
while [ $# -gt 0 ]; do
  PKG_SCRIPTNAME=$1
  shift

  PKG_ARCH=x86_64
  export CPP=cpp
  export AR=ar
  export AS=as
  export NM=nm
  export CC=gcc
  export CXX=g++
  export LD=ld
  export RANLIB=ranlib
  export STRIP=strip
  export CFLAGS="-O2 ${CFLAGS}"
  export CXXFLAGS="-O2 ${CXXFLAGS}"
  export PKG_OS=linux
  export PKG_ARCH=x86_64

  ./$PKG_SCRIPTNAME
done
