#!/bin/sh
set -e
if [ $# -lt 1 ]; then
    echo "$0 i386|x86_64 [command [args...]]" 1>&2
    exit 1
fi
PKG_ARCH=$1
shift
if [ "$PKG_ARCH" = "i386" ]; then
  TOOLCHAIN_NAME=i686-w64-mingw32
elif [ "$PKG_ARCH" = "x86_64" ]; then
  TOOLCHAIN_NAME=x86_64-w64-mingw32
else
  echo "$0: unsupported architecture: $PKG_ARCH" 1>&2
  exit 1
fi
export CPP=$TOOLCHAIN_NAME-cpp
export AR=$TOOLCHAIN_NAME-ar
export AS=$TOOLCHAIN_NAME-as
export NM=$TOOLCHAIN_NAME-nm
export CC=$TOOLCHAIN_NAME-gcc
export CXX=$TOOLCHAIN_NAME-g++
export LD=$TOOLCHAIN_NAME-ld
export RANLIB=$TOOLCHAIN_NAME-ranlib
export STRIP=$TOOLCHAIN_NAME-strip
export PKG_CONFIGUREFLAGS="--host=$TOOLCHAIN_NAME"
export CFLAGS="-O2 ${CFLAGS}"
export CXXFLAGS="-O2 ${CXXFLAGS}"
export PKG_OS=mingw
export PKG_ARCH
if [ $# -gt 0 ]; then
    $@
else
    env
fi
