#!/bin/sh
set -e

docker build -t mk-script-build-unix .

mkdir -p MK_DIST
mkdir -p MK_BUILD

docker run \
    -v $PWD/MK_DIST:/mk-build/MK_DIST \
    -v $PWD/MK_BUILD/:/mk-build/MK_BUILD \
    -t mk-script-build-unix \
    /bin/sh -c 'cd /mk-build && ./build-linux `./all-deps.sh` measurement-kit'

docker run \
    -v $PWD/MK_DIST:/mk-build/MK_DIST \
    -v $PWD/MK_BUILD/:/mk-build/MK_BUILD \
    -t mk-script-build-unix \
    /bin/sh -c 'cd /go/src/measurement-kit/go-measurement-kit/ && cp -R /mk-build/MK_DIST ./libs/MK_DIST && make test'
