#!/bin/bash
set -e
curdir=`pwd -P`
while [ $# -gt 0 ]; do
  package=$1
  shift
  if [ ! -d MK_DIST/ios/$package ]; then
    echo "FATAL: no builds of $package available" 1>&2
    exit 1
  fi
  for version in `ls MK_DIST/ios/$package`; do
    versionedpackagedir=MK_DIST/ios/$package/$version

    # Gather library all the library names for all architectures
    libs=""
    for arch in `ls $versionedpackagedir`; do
      for lib in `ls $versionedpackagedir/$arch/lib`; do
        libs="$libs $lib"
      done
    done
    libs=`echo $libs | tr ' ' '\n' | sort -u`

    # Make sure that all architectures have all libs
    for arch in `ls $versionedpackagedir`; do
      for lib in $libs; do
        if [ ! -f $versionedpackagedir/$arch/lib/$lib ]; then
          echo "FATAL: missing $lib for $package@$version with $arch" 1>&2
          exit 1
        fi
      done
    done

    # Create a framework for each lib
    for lib in $libs; do
      framework=`echo $lib | sed 's/\.a$//g'`
      frameworkdir=$curdir/Framework/$framework.framework
      rm -rf $frameworkdir
      install -d $frameworkdir
      lipo -create -output $frameworkdir/$framework                            \
        `find $versionedpackagedir -type f -name $lib`

      # Copy headers of the first arch for the current framework
      install -d $frameworkdir/Headers
      for headers_arch in `ls $versionedpackagedir`; do
        cp -Rp $versionedpackagedir/$headers_arch/include/ $frameworkdir/Headers
        break  # just the first arch
      done

      headers_match=1
      for headers_arch in `ls $versionedpackagedir`; do
        if ! diff -qru $frameworkdir/Headers                                   \
            $versionedpackagedir/$headers_arch/include; then
          headers_match=0
        fi
      done
      if [ $headers_match -eq 0 ]; then
        echo "WARNING: Arch headers do not match, using per arch includes"
        rm -rf $frameworkdir/Headers
        install -d $frameworkdir/Headers
        for headers_arch in `ls $versionedpackagedir`; do
          cp -Rp $versionedpackagedir/$headers_arch/include/                   \
            $frameworkdir/Headers/$headers_arch
        done
      fi

    done
  done
done
