#!/bin/sh
set -ex
PKG_TOPDIR=$(cd $(dirname $0) && pwd -P)
cd $PKG_TOPDIR
PKG_NAME=geoip-api-c
PKG_VERSION=1.6.12
PKG_CHECKSUM=99b119f8e21e94f1dfd6d49fbeed29a70df1544896e76cd456f25e397b07d476
PKG_URL=https://github.com/maxmind/geoip-api-c/archive/v$PKG_VERSION.tar.gz
PKG_BUILD=8
[ "$PKG_OS" != "" -a "$PKG_ARCH" != "" ]
PKG_FULLNAME=$PKG_NAME/$PKG_VERSION-$PKG_BUILD
PKG_BUILDDIR=$PKG_TOPDIR/MK_BUILD/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
PKG_INSTALLDIR=$PKG_TOPDIR/MK_DIST/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
rm -rf $PKG_BUILDDIR $PKG_INSTALLDIR
install -d $PKG_BUILDDIR $PKG_INSTALLDIR
(
  set -ex
  cd $PKG_BUILDDIR
  curl -fsSLO $PKG_URL
  REAL_CHECKSUM=$(shasum -a 256 v$PKG_VERSION.tar.gz | awk '{print $1}')
  [ $PKG_CHECKSUM = "$REAL_CHECKSUM" ]
  tar -xzf v$PKG_VERSION.tar.gz
  cd $PKG_NAME-$PKG_VERSION
  ./bootstrap
  # See measurement-kit/measurement-kit#518
  export ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes
  ./configure --prefix=/ --disable-shared $PKG_CONFIGUREFLAGS
  make V=0
  make install DESTDIR=$PKG_INSTALLDIR
  rm -rf $PKG_INSTALLDIR/bin
  rm -rf $PKG_INSTALLDIR/lib/pkgconfig
  rm -rf $PKG_INSTALLDIR/lib/libGeoIP.la
  rm -rf $PKG_INSTALLDIR/share
)
