#!/bin/sh
set -e
CURRENT_DIR=$(pwd -P)
PKG_TOPDIR=$(cd $(dirname $0) && pwd -P)
PKG_REPO=https://github.com/measurement-kit/script-build-unix/releases/download
PKG_CHANNEL=v0.3.0
while [ $# -gt 0 ]; do
  REGEX='^(android|ios|linux|macos|mingw)'
  if ! echo $1 | grep -Eq $REGEX; then
    echo "FATAL: package stem does not match: $REGEX" 1>&2
    exit 1
  fi
  PKG_TARBALL=`cat $PKG_TOPDIR/SHA256SUMS | grep $1 | awk '{print $2}'|tail -n1`
  if [ "$PKG_TARBALL" = "" ]; then
    echo "FATAL: No package named: $1" 1>&2
    exit 1
  fi
  shift
  echo "Installing $PKG_TARBALL from $PKG_CHANNEL"
  set -x
  rm -rf $PKG_TARBALL
  curl -fsSLO $PKG_REPO/$PKG_CHANNEL/$PKG_TARBALL
  REAL_CHECKSUM=`shasum -a 256 $PKG_TARBALL | awk '{print $1}'`
  EXPECTED=`grep $PKG_TARBALL $PKG_TOPDIR/SHA256SUMS | awk '{print $1}'`
  [ "$REAL_CHECKSUM" = "$EXPECTED" ]
  tar -xzf $PKG_TARBALL
  rm -rf $PKG_TARBALL
  set +x
done
echo "All packages installed in: $CURRENT_DIR/MK_DIST"
