#!/bin/sh
set -ex
PKG_TOPDIR=$(cd $(dirname $0) && pwd -P)
PKG_NAME=measurement-kit
PKG_VERSION=0.9.0-alpha.2
PKG_CHECKSUM=dfb31a9e654e6e3ec3ddb0231decafef7732c223b07eca90c30ac354fb344dd2
PKG_URL=https://github.com/measurement-kit/measurement-kit/archive/v$PKG_VERSION.tar.gz
PKG_BUILD=2
[ "$PKG_OS" != "" -a "$PKG_ARCH" != "" ]
PKG_FULLNAME=$PKG_NAME/$PKG_VERSION-$PKG_BUILD
PKG_BUILDDIR=$PKG_TOPDIR/MK_BUILD/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
PKG_INSTALLDIR=$PKG_TOPDIR/MK_DIST/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
PKG_GEOIP_VERSION=1.6.12-3
PKG_LIBRESSL_VERSION=2.6.4-4
PKG_LIBEVENT_VERSION=2.1.8-4
rm -rf $PKG_BUILDDIR $PKG_INSTALLDIR
install -d $PKG_BUILDDIR $PKG_INSTALLDIR
(
  set -ex
  cd $PKG_BUILDDIR
  curl -LsO $PKG_URL
  REAL_CHECKSUM=$(shasum -a 256 v$PKG_VERSION.tar.gz | awk '{print $1}')
  [ $PKG_CHECKSUM = "$REAL_CHECKSUM" ]
  tar -xzf v$PKG_VERSION.tar.gz
  cd $PKG_NAME-$PKG_VERSION
  ./autogen.sh -n
  GEOIP_PREFIX=$PKG_TOPDIR/MK_DIST/$PKG_OS/geoip-api-c/$PKG_GEOIP_VERSION/$PKG_ARCH/
  LIBRESSL_PREFIX=$PKG_TOPDIR/MK_DIST/$PKG_OS/libressl/$PKG_LIBRESSL_VERSION/$PKG_ARCH/
  LIBEVENT_PREFIX=$PKG_TOPDIR/MK_DIST/$PKG_OS/libevent/$PKG_LIBEVENT_VERSION/$PKG_ARCH/
  ./configure --prefix=/ --disable-shared --disable-examples                   \
    --disable-binaries --with-geoip=$GEOIP_PREFIX                              \
    --with-libevent=$LIBEVENT_PREFIX --with-openssl=$LIBRESSL_PREFIX           \
    $PKG_CONFIGUREFLAGS CPPFLAGS="$CPPFLAGS -Wno-cpp"
  make V=0
  make install DESTDIR=$PKG_INSTALLDIR
  rm -rf $PKG_INSTALLDIR/lib/libmeasurement_kit.la
  rm -rf $PKG_INSTALLDIR/include/measurement_kit/README.md
)
