#!/bin/sh
set -e
if [ $# -ne 1 ]; then
  echo "" 1>&2
  echo "Usage: $0 ARCH" 1>&2
  echo "" 1>&2
  echo "  ARCH: armeabi-v7a, arm64, x86, x86_64" 1>&2
  echo "" 1>&2
  exit 1
fi

ROOTDIR=$(cd $(dirname $0) && pwd -P)
export NDK_ROOT=`$ROOTDIR/config-android-ndk-root`
if [ "$NDK_ROOT" = "" ]; then
  echo "FATAL: unable to determine NDK_ROOT; please export NDK_ROOT=/path." 1>&2
  exit 1
fi

ARCH=$1
shift
BASEDIR=$ROOTDIR/MK_BUILD/toolchain/android

# Directory where to install the toolchain. This must be done _before_
# mapping the input architecture to a real toolchain architecture.
INSTALL_DIR=$BASEDIR/${ARCH}

# Map input architecture to toolchain architecture
if [ "$ARCH" = "armeabi-v7a" ]; then
  ARCH="arm"
fi

API=`$ROOTDIR/config-android-api $ARCH`
if [ "$API" = "" ]; then
  echo "FATAL: unable to determine API for $ARCH" 1>&2
  exit 1
fi

MAKE_TOOLCHAIN=${NDK_ROOT}/build/tools/make_standalone_toolchain.py
echo "Creating toolchain for API ${API} and ARCH ${ARCH} in ${INSTALL_DIR}"
$MAKE_TOOLCHAIN --arch=${ARCH} --api=${API} --install-dir=${INSTALL_DIR}       \
    --stl=libc++ --force
