#!/bin/sh
set -e
if [ $# -ne 1 ]; then
  echo "" 1>&2
  echo "Usage: $0 ARCH" 1>&2
  echo "" 1>&2
  echo "  ARCH: armeabi-v7a, arm64, x86, x86_64" 1>&2
  echo "" 1>&2
  exit 1
fi
if [ "$NDK_ROOT" = "" ]; then
  echo "FATAL: you must set NDK_ROOT" 1>&2
  exit 1
fi

ROOTDIR=$(cd $(dirname $0) && pwd -P)
ARCH=$1
shift
BASEDIR=$ROOTDIR/MK_BUILD/toolchain/android

# Directory where to install the toolchain. This must be done _before_
# mapping the input architecture to a real toolchain architecture.
INSTALL_DIR=$BASEDIR/${ARCH}

# Map input architecture to toolchain architecture
if [ "$ARCH" = "armeabi-v7a" ]; then
  ARCH="arm"
fi

# See https://github.com/measurement-kit/measurement-kit/pull/1554#discussion_r167493143
if [ "$ARCH" = "arm64" -o "$ARCH" = "mips64" -o "$ARCH" = "x86_64" ]; then
  API=21
else
  API=16
fi

MAKE_TOOLCHAIN=${NDK_ROOT}/build/tools/make_standalone_toolchain.py
echo "Creating toolchain for API ${API} and ARCH ${ARCH} in ${INSTALL_DIR}"
$MAKE_TOOLCHAIN --arch=${ARCH} --api=${API} --install-dir=${INSTALL_DIR}       \
    --stl=libc++ --force
